server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: dayo-system

  main:
    allow-bean-definition-overriding: true

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/worklog?serverTimezone=UTC
      username: root
      password: 123456

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000ms  #redis请求超时时间，超过此值redis自动断开连接
    jedis:
      pool:
        max-active: 32 #jedis最大连接数，超过此值则提示获取不到连接异常
        max-wait: 100ms #jedis最大等待时间，超过此值会提示连接超时异常
        max-idle: 32 #jedis最大等待连接数
        min-idle: 0 #jedis最小等待连接数
