server:
  port: 9004
spring:
  main:
    allow-bean-definition-overriding: true #
#Description:
#The bean 'clientDetailsService', defined in class path resource [cn/caishen/auth2/config/AuthServerConfig.class], could not be registered. A bean with that name has already been defined in BeanDefinition defined in class path resource [org/springframework/security/oauth2/config/annotation/configuration/ClientDetailsServiceConfiguration.class] and overriding is disabled.
#Action:
#Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true    
    
  application:
    name: dayo-auth2 
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/worklog?serverTimezone=UTC
    username: root
    password: root    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
