server:
  port: 9004

spring:
  application:
    name: dayo-auth
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/worklog?serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#nacos两种配置方法：
#nacos.discovery.server-addr=127.0.0.1:8848
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka/
#    registry-fetch-interval-seconds: 5
#  instance:
#    ip-address: 127.0.0.1
#    prefer-ip-address: true

dayo:
  jwt:
    pubKeyPath: D:/Code/dayo_parent/temp/ssh/id_rsa.pub # 公钥地址
    priKeyPath: D:/Code/dayo_parent/temp/ssh/id_rsa # 私钥地址
    user:
      expire: 30 # 过期时间,单位分钟
      cookieName: dayoToken # cookie名称
      cookieDomain: caishen.cn # cookie的域