server:
  port: 9000


eureka:
  instance:
    hostname: dayo-registry
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  application:
    name: dayo-registry

