server:
  port: 80
spring:
  application:
    name: dayo-zuul

#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 10000ms  #redis请求超时时间，超过此值redis自动断开连接
#    jedis:
#      pool:
#        max-active: 32 #jedis最大连接数，超过此值则提示获取不到连接异常
#        max-wait: 100ms #jedis最大等待时间，超过此值会提示连接超时异常
#        max-idle: 32 #jedis最大等待连接数
#        min-idle: 0 #jedis最小等待连接数

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 5
    fetch-registry: true

hystrix:
  threadpool:
    default:
      coreSize: 500  #并发执行的最大线程数，默认10
  command:
    paas-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3600000
            strategy: SEMAPHORE
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000  #命令执行超时时间，默认1000ms

ribbon:
  ConnectTimeout: 5000 # ribbon链接超时时长
  ReadTimeout: 5000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
  eureka:
    enabled: true


zuul:
  ignoredServices: '*' #忽略所有未配置的service
  ignore-security-headers: false  #不忽略框架与权限相关的头信息
  routes:
    dayo-worklog:
      path: /worklog/**
      serviceId: dayo-worklog
      sensitiveHeaders: "*"

    dayo-system:
      path: /system/**
      serviceId: dayo-system
      sensitiveHeaders: "*"

    dayo-auth:
      path: /auth/**
      serviceId: dayo-auth
      sensitiveHeaders: "*"
    
    dayo-auth2:
      path: /uaa/**
      serviceId: dayo-auth2
      sensitiveHeaders: "*"    
      
    dayo-example:
      path: /example/**
      serviceId: dayo-example
      sensitiveHeaders: "*"            

  host:
    maxTotalConnections: 10000
    maxPerRouteConnections: 10000
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

  semaphore:
    max-semaphores: 200

  sensitive-headers: #把默认的敏感头集合设置为空